// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApplication_Learning.Data;

#nullable disable

namespace WebApplication_Learning.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260403152814_MarketIdOpcional")]
    partial class MarketIdOpcional
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AccountModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer")
                        .HasColumnName("age");

                    b.Property<int>("MarketId")
                        .HasColumnType("integer")
                        .HasColumnName("market_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("MarketId")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_market_id");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("MarketModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_markets");

                    b.ToTable("markets", (string)null);
                });

            modelBuilder.Entity("ProductModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("MarketId")
                        .HasColumnType("integer")
                        .HasColumnName("market_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("MarketId")
                        .HasDatabaseName("ix_products_market_id");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("AccountModel", b =>
                {
                    b.HasOne("MarketModel", "Market")
                        .WithOne("Account")
                        .HasForeignKey("AccountModel", "MarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_accounts_markets_market_id");

                    b.Navigation("Market");
                });

            modelBuilder.Entity("ProductModel", b =>
                {
                    b.HasOne("MarketModel", "Market")
                        .WithMany("Products")
                        .HasForeignKey("MarketId")
                        .HasConstraintName("fk_products_markets_market_id");

                    b.Navigation("Market");
                });

            modelBuilder.Entity("MarketModel", b =>
                {
                    b.Navigation("Account");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
